import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/libs/utils";
import Navbar from "./components/Navbar"; // Import Navbar here

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn(
        'min-h-screen font-sans antialiased grainy',
        inter.className,
      )}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
